env:
  browser: true
  commonjs: true
extends: 'eslint:recommended'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  no-unused-vars:
    - off
  eqeqeq:
    - error
